steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files:
          - hooks/**

  - label: ":shell: Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: docker-compose

  - label: ":shell: Tests"
    plugins:
      docker-compose#2.4.1:
        run: tests
