steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.3.0:
        files:
          - hooks/**

  - label: ":shell: Lint"
    plugins:
      plugin-linter#v3.1.0:
        id: git-clean

  - label: ":shell: Tests"
    plugins:
      docker-compose#v4.9.0:
        run: tests
